---
# handlers file for molecule-cinder
- name: restart ntp
  service:
    name: "{{ ntp_daemon }}"
    state: restarted

- name: restart cinder-volume service
  become: true
  service:
    name: "cinder-volume"
    state: restarted
