---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: False
    login_cmd_template: 'ssh {instance}'
    ansible_connection_options:
      connection: ssh
lint:
  name: yamllint
platforms:
  - name: 172.20.41.98
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  connection_options:
    ansible_ssh_user: ubuntu
    ansible_ssh_common_args: -o IdentitiesOnly=no
    become: true
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
